export const GET_PRODUCTS = "getProducts"
export const ADD_PRODUCT = "addProduct"
export const EDIT_PRODUCT = "editProduct"
export const DELETE_PRODUCT = "deleteProduct"
export const GET_DELETED_PRODUCT = "getDeleteProduct"